name: image-searcher
on: [push]
jobs:
    bandit:
        name: bandit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-python@master
              with:
                  python-version: 3.8.6
            - run: python -m pip install --upgrade pip
            - run: pip install -r requirements.txt
            - run: poetry install
            - run: sh util.sh bandit
    flake8:
        name: flake8
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-python@master
              with:
                  python-version: 3.8.6
            - run: python -m pip install --upgrade pip
            - run: pip install -r requirements.txt
            - run: poetry install
            - run: sh util.sh flake8
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-python@master
              with:
                  python-version: 3.8.6
            - run: python -m pip install --upgrade pip
            - run: pip install -r requirements.txt
            - run: poetry install
            - run: sh util.sh test
    push-container:
        name: push-container
        runs-on: ubuntu-latest
        needs: [bandit, flake8, test]
        steps:
            - uses: actions/checkout@master
            - run: docker build . --file Dockerfile --tag docker.pkg.github.com/doara-developer/image-searcher/image-searcher:latest
            - run: docker login docker.pkg.github.com -u doara-developer -p ${{ secrets.DEPLOY_TOKEN }}
            - run: docker push docker.pkg.github.com/doara-developer/image-searcher/image-searcher:latest
